use_frameworks!
platform :ios, '9.0'

def standard_pods
    pod 'SNPNetwork', :path => '../'
    pod 'Alamofire', '~> 4.7'
end

target 'SNPNetwork_Example' do
  standard_pods
  pod 'SNPUtilities'
end

target 'SNPNetwork_Tests' do
    inherit! :search_paths
    standard_pods
    pod 'SNPUtilities'
end
