use_frameworks!
platform :ios, '9.0'

def shared_pods
    pod 'SNPNetwork', :path => '../'
    pod 'Alamofire', '~> 4.7'
    pod 'SNPUtilities', :git => 'https://github.com/snapp-cab/SNPUtilities.git', :branch => 'dev'
end

target 'SNPNetwork_Example' do
    shared_pods
end

target 'SNPNetwork_Tests' do
    inherit! :search_paths
    shared_pods
end
